// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU3y2JFUW-rV2qYhn13m-LPRKPsDP83zc',
    appId: '1:63376744840:web:4c28ff291cebec1d715a3d',
    messagingSenderId: '63376744840',
    projectId: 'ai-pencil',
    authDomain: 'ai-pencil.firebaseapp.com',
    storageBucket: 'ai-pencil.appspot.com',
    measurementId: 'G-8V74S2BKWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7yNHW9h9iifjW2dOidBjHiH_NLiVVbsY',
    appId: '1:63376744840:android:2d74a7979809becf715a3d',
    messagingSenderId: '63376744840',
    projectId: 'ai-pencil',
    storageBucket: 'ai-pencil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC13fove4BfDdWGbBike9LVU4EXs7-cmgQ',
    appId: '1:63376744840:ios:20d6c0dfb4c5586c715a3d',
    messagingSenderId: '63376744840',
    projectId: 'ai-pencil',
    storageBucket: 'ai-pencil.appspot.com',
    iosClientId: '63376744840-pnrtl8q14mvluqbjf8215kkif10v9l37.apps.googleusercontent.com',
    iosBundleId: 'io.aipencil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC13fove4BfDdWGbBike9LVU4EXs7-cmgQ',
    appId: '1:63376744840:ios:20d6c0dfb4c5586c715a3d',
    messagingSenderId: '63376744840',
    projectId: 'ai-pencil',
    storageBucket: 'ai-pencil.appspot.com',
    iosClientId: '63376744840-pnrtl8q14mvluqbjf8215kkif10v9l37.apps.googleusercontent.com',
    iosBundleId: 'io.aipencil',
  );
}
